apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apa-ia-tls
  namespace: apa
spec:
  dnsNames:
  - plataforma-integrada-dev.nees.ufal.br
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: apa-ia-tls
  duration: 8640h
  renewBefore: 7440h
