apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apa-machine-learning
  namespace: apa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apa-machine-learning
  targetCPUUtilizationPercentage: 70


